VOLUME = qc
USERESOURCESFOR = plf
VOLUMENAME = PBT in Coq
VERSION = 1.0

TOP = $(HOME)/s/new

# (The order here determines the order of chapters in the
# generated table of contents.)
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# IMPORTANT!!!  If you add a file here, make sure to do
#    svn add <new files>
#    svn propset svn:keywords Date *.v
# and fix up the dependencies in deps.dot
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
EXPORTS = \
	   Typeclasses.v \

#	   Bib.v \

MORETAGS = TODO 

# Grab the common parts of the build procedure from upstairs
include $(TOP)/Common.Makefile

