VOLUME = qc
USERESOURCESFOR = plf
VOLUMENAME = PBT in Coq
VERSION = 1.0

# This will only work for BCP:
TOP = $(HOME)/s/new

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# IMPORTANT!!!  If you add a file here, make sure to do
#    svn add <new files>
#    svn propset svn:keywords Date *.v
# and fix up the dependencies in deps.dot
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
EXPORTS = \
	   Preface.v \
	   Introduction.v \
	   Typeclasses.v \
	   Bib.v \

MORETAGS = TODO 

# Grab the common parts of the build procedure from upstairs
include $(TOP)/Common.Makefile

