#!/bin/sh
# Usage: mycppo input.v.cppo output.v

COQVER=$(coqc -print-version)
COQVER=${COQVER%% *}
printf "#!/bin/sh\ncppo -V OCAML:$(ocamlc -version) -V COQ:$COQVER -n \$1 -o \$2" > mycppo
chmod u+x mycppo
